### ISSUE TITLE
Build error with GCC9: error: '%s' directive argument is null when using -format-overflow

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1324]
In the next Fedora release this could be an issue, but it isn't a problem yet for the majority that are still on gcc7/8. Mozilla is also [tracking gcc9](https://bugzilla.mozilla.org/show_bug.cgi?id=1514781), but hasn't reported this particular issue as far as I can tell.

Logging this bug here for reference.

```
In file included from /UXP/js/src/jit/x86-shared/Assembler-x86-shared.h:17,
                 from /UXP/js/src/jit/x64/Assembler-x64.h:248,
                 from /UXP/js/src/jit/x86-shared/MacroAssembler-x86-shared.h:15,
                 from /UXP/js/src/jit/x64/MacroAssembler-x64.h:12,
                 from /UXP/js/src/jit/MacroAssembler.h:18,
                 from /UXP/js/src/jit/BaselineJIT.h:18,
                 from /UXP/js/src/jit/BaselineIC.h:20,
                 from /UXP/js/src/jit/MIR.h:21,
                 from /UXP/js/src/jit/AlignmentMaskAnalysis.cpp:8,
                 from /UXP/ff/js/src/Unified_cpp_js_src8.cpp:2:
In member function 'void js::jit::X86Encoding::BaseAssemblerX64::movq_mr(int32_t, js::jit::X86Encoding::RegisterID, js::jit::X86Encoding::RegisterID, int, js::jit::X86Encoding::RegisterID)',
    inlined from 'void js::jit::Assembler::movq(const js::jit::Operand&, js::jit::Register)' at /UXP/js/src/jit/x64/Assembler-x64.h:397:25:
/UXP/js/src/jit/x64/BaseAssembler-x64.h:596:13: error: '%s' directive argument is null [-Werror=format-overflow=]
  596 |         spew("movq       " MEM_obs ", %s", ADDR_obs(offset, base, index, scale), GPReg64Name(dst));
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /UXP/js/src/jit/x86-shared/BaseAssembler-x86-shared.h:35,
                 from /UXP/js/src/jit/x64/BaseAssembler-x64.h:10,
                 from /UXP/js/src/jit/x86-shared/Assembler-x86-shared.h:17,
                 from /UXP/js/src/jit/x64/Assembler-x64.h:248,
                 from /UXP/js/src/jit/x86-shared/MacroAssembler-x86-shared.h:15,
                 from /UXP/js/src/jit/x64/MacroAssembler-x64.h:12,
                 from /UXP/js/src/jit/MacroAssembler.h:18,
                 from /UXP/js/src/jit/BaselineJIT.h:18,
                 from /UXP/js/src/jit/BaselineIC.h:20,
                 from /UXP/js/src/jit/MIR.h:21,
                 from /UXP/js/src/jit/AlignmentMaskAnalysis.cpp:8,
                 from /UXP/ff/js/src/Unified_cpp_js_src8.cpp:2:
/UXP/js/src/jit/x86-shared/AssemblerBuffer-x86-shared.h: In function 'void js::jit::Assembler::movq(const js::jit::Operand&, js::jit::Register)':
/UXP/js/src/jit/x86-shared/AssemblerBuffer-x86-shared.h:46:32: note: format string is defined here
   46 | #define MEM_obs   MEM_o   "(%s,%s,%d)"
      |                                ^~

```

**Comment by trav90** [comment]
Pale Moon or Basilisk? Exactly which version of GCC 9? I built Pale Moon successfully using GCC 9.2.0 earlier today.

**Comment by wolfbeast** [comment]
Doesn't make sense for it to error on that, as it's exactly the same as the other `spew()` commands in that same header that are fine. Compiler bug?

**Comment by g4jc** [comment]
> Exactly which version of GCC 9 did you use? I built Pale Moon successfully using GCC 9.2.0 earlier today.

gcc (Gentoo Hardened 9.2.0-r2 p3) 9.2.0.

>  Compiler bug?

Possibly, it's an odd issue.

**Comment by mattatobin** [comment]
@g4jc You cited Fedora in the opening post.. Does it build on rawhide, cause a few months ago it did.

**Comment by intc** [comment]
I'm on `gcc version 9.2.0 (Gentoo Hardened 9.2.0-r2 p3)`.
Git commit: `ce0dd36a78814c59950fde6c19413c1f7ea85ee1`
It builds OK but `./mach package` fails:
```
 0:02.87 resource://gre/modules/PlacesTransactions.jsm
 0:02.88 JavaScript error: resource://gre/components/nsPrompter.js, line 364: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowWatcher.openWindow]
 0:02.89 Traceback (most recent call last):
 0:02.89   File "/home/user/o-github/UXP/toolkit/mozapps/installer/packager.py", line 416, in <module>
 0:02.89     main()
 0:02.89   File "/home/user/o-github/UXP/toolkit/mozapps/installer/packager.py", line 410, in main
 0:02.89     args.source, gre_path, base)
 0:02.89   File "/home/user/o-github/UXP/toolkit/mozapps/installer/packager.py", line 166, in precompile_cache
 0:02.89     errors.fatal('Error while running startup cache precompilation')
 0:02.89   File "/home/user/o-github/UXP/python/mozbuild/mozpack/errors.py", line 103, in fatal
 0:02.89     self._handle(self.FATAL, msg)
 0:02.89   File "/home/user/o-github/UXP/python/mozbuild/mozpack/errors.py", line 98, in _handle
 0:02.89     raise ErrorMessage(msg)
 0:02.89 mozpack.errors.ErrorMessage: Error: Error while running startup cache precompilation
```

**Comment by mattatobin** [comment]
That is something else. Use `--disable-startupcache` if you run into this.

**Comment by g4jc** [comment]
@intc could you confirm if it builds using [iceweasel-uxp-9999.ebuild](https://github.com/g4jc/iceweasel-uxp-overlay)? I was also able to get it to build using mach build only, but Gentoo still uses the `emake -f client.mk realbuild` if it matters.

emerge --info:

```
www-client/iceweasel-uxp-9999::local-overlay was built with the following:
USE="hardened jemalloc privacy system-bz2 system-ffi system-hunspell system-icu system-jpeg system-pixman system-zlib -custom-cflags -custom-optimization -dbus -debug -gtk2 -hwaccel -jack (-neon) -pgo -pulseaudio (-selinux) -startup-notification -system-cairo -system-harfbuzz -system-libevent -system-libvpx -system-sqlite -test -wifi"
```


I'm setting up a new Fedora rawhide environment later today to confirm if this is happening over there.

**Comment by intc** [comment]
@mattatobin: Ok. Thanks!

**Comment by intc** [comment]
@g4jc, I modified the ebuild and added a patch to allow configuration to pass through.

This build fails:

```
In member function 'void js::jit::X86Encoding::BaseAssemblerX64::movq_mr(int32_t, js::jit::X86Encoding::RegisterID, js::jit::X86Encoding::RegisterID, int, js::jit::X86Encoding::RegisterID)',
    inlined from 'void js::jit::Assembler::movq(const js::jit::Operand&, js::jit::Register)' at /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x64/Assembler-x64.h:397:25:
/var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x64/BaseAssembler-x64.h:596:13: error: '%s' directive argument is null [-Werror=format-overflow=]
  596 |         spew("movq       " MEM_obs ", %s", ADDR_obs(offset, base, index, scale), GPReg64Name(dst));
      |         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x86-shared/BaseAssembler-x86-shared.h:35,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x64/BaseAssembler-x64.h:10,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x86-shared/Assembler-x86-shared.h:17,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x64/Assembler-x64.h:248,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x86-shared/MacroAssembler-x86-shared.h:15,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x64/MacroAssembler-x64.h:12,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/MacroAssembler.h:18,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/BaselineJIT.h:18,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/BaselineIC.h:20,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/MIR.h:21,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/AlignmentMaskAnalysis.cpp:8,
                 from /var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/o/js/src/Unified_cpp_js_src8.cpp:2:
/var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x86-shared/AssemblerBuffer-x86-shared.h: In function 'void js::jit::Assembler::movq(const js::jit::Operand&, js::jit::Register)':
/var/tmp/portage/www-client/iceweasel-uxp-9999/work/iceweasel-uxp-9999/js/src/jit/x86-shared/AssemblerBuffer-x86-shared.h:46:32: note: format string is defined here
   46 | #define MEM_obs   MEM_o   "(%s,%s,%d)"
      |                                ^~
```

**Comment by mattatobin** [comment]
Seems like what most are doing including Mozilla is just overriding the error with `-Wno-error=format-overflow` and seems specific to JUST GCC 9.2.0 whereas Fedora 9.2.1 doesn't have this issue.

So what we should likely do is use that flag for js but ONLY GCC 9.2.0. I can't get anymore specific than that because of that single massive `moz.build` file and `UNIFIED_SOURCES`.

I am waiting for absolute verification from @g4jc then I will commit a small patch to workaround this for `GCC 9.2.0`.

**Comment by mattatobin** [comment]
We are trying to figure out why distros have a `GCC 9.2.1` (which does not seem to suffer from this) but GCC people them selves haven't formally released one.

**Comment by g4jc** [comment]
For what it's worth the nightly gcc-git (a.k.a. 10.0.0_pre) does *not* fail on that code line. However, it fails much later on a completely unrelated and vague linker error. So, I'm going to go ahead and assume this odd bug only affects gcc 9.2.0.

**Comment by mattatobin** [comment]
This seems to be isolated to a Gentoo Hardened Profile configuration. Base Gentoo as reported by @deu seems to be ok as does Debian and Fedora Rawhide's `GCC 9.2.x`. So because of this and the nature of Gentoo as a hobbyist from source distribution where you have to figure stuff out.. They should just patch locally.

I am recommending `RESOLVED WONTFIX` in this case.

What is your opinion @wolfbeast @g4jc @trav90

**Comment by wolfbeast** [comment]
Hardened Gentoo is not our problem to fix, IMO. If it kills gcc usability then you can always use a supplied generic binary instead of building your own.
Welcome to the pain of using gentoo (or any LFS) which isn't a standard Linux environment.

**Comment by g4jc** [comment]
Since `format-overflow` seems to be an overly aggressive gcc flag and is probably an edge case, I tend to agree it's best to close and just use @mattatobin's [patch](https://github.com/MoonchildProductions/UXP/issues/1324#issuecomment-566861762) locally. Even Firefox is shipping with `-Wno-error=format-overflow` as of the moment.

**Comment by trav90** [comment]
I agree with the `WONTFIX` recommendation. This is a very corner case on a very specific distro using a specific compiler configuration and as such I don't believe it is our problem to fix. Especially when a standard GCC 9.2.x builds Pale Moon just fine.

**Comment by mattatobin** [comment]
**`RESOLVED WONTFIX`**
