### ISSUE TITLE
The codebase won't build without DevTools Server because of heapsnapshot

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#316]
Seems DOM expects `devtools/shared/heapsnapshot` to be there. I know it is absolutely required for DevTools them selves but I need to investigate anything else that might expect it and if nothing.. Make the DOM code that uses it conditional.

- [x] Figure out what the hell `heapsnapshot` actually is and if we want to keep it
- [x] Always build `heapsnapshot` regardless of the rest of the devtools for now
- [x] Make the DOM bits conditional
- [x] Move headsnapshot into DOM

**Comment by wolfbeast** [comment]
I think it's used for the API behind the pref `dom.enable_memory_stats` which allows content scripts to measure e.g. heap memory in use. It should be considered part of devtools (and then specifically for developing the applications themselves), so making the dom parts using this conditional would be the way to go.

**Comment by wolfbeast** [comment]
Needs a follow-up

**Comment by mattatobin** [comment]
Because of ipdl the core of this issue cannot be resolved.

What is going to happen is heapsnspshot is going to be moved into dom as it seems to really want to be a dom component.

We can revisit this in the future if a breakthrough happens.

**Comment by wolfbeast** [comment]
Adjusted the initial post accordingly

**Comment by JustOff** [comment]
This issue seems to be cursed by an evil witch:

```
 0:40.75 Creating config.status
 0:40.75 Feeding the hatchlings...
 0:46.06 Traceback (most recent call last):
 0:46.06   File "d:/Pale-Moon/configure.py", line 32, in <module>
 0:46.06     sys.exit(main(sys.argv))
 0:46.07   File "d:/Pale-Moon/configure.py", line 29, in main
 0:46.08     return config_status(config)
 0:46.08   File "d:\Pale-Moon\platform\configure.py", line 102, in config_status
 0:46.09     return config_status(args=[], **encode(sanitized_config, encoding))
 0:46.09   File "d:\Pale-Moon\platform\python\mozbuild\mozbuild\config_status.py", line 148, in config_status
 0:46.10     definitions = list(definitions)
 0:46.10   File "d:\Pale-Moon\platform\python\mozbuild\mozbuild\frontend\emitter.py", line 169, in emit
 0:46.11     for out in output:
 0:46.11   File "d:\Pale-Moon\platform\python\mozbuild\mozbuild\frontend\reader.py", line 1066, in read_mozbuild
 0:46.12     raise bre
 0:46.12 mozbuild.frontend.reader.BuildReaderError:
 0:46.13 ==============================
 0:46.13 ERROR PROCESSING MOZBUILD FILE
 0:46.13 ==============================
 0:46.14
 0:46.14 The error occurred while processing the following file:
 0:46.15
 0:46.15     d:/Pale-Moon/platform/dom/heapsnapshot/moz.build
 0:46.16
 0:46.16 The error was triggered on line 52 of this file:
 0:46.17
 0:46.17     DevToolsModules(
 0:46.18
 0:46.18 An error was encountered as part of executing the file itself. The error appears to be the fault of the script.

 0:46.19
 0:46.19 The error as reported by Python is:
 0:46.20
 0:46.20     ["NameError: name 'DevToolsModules' is not defined\n"]
 0:46.21
 0:46.21 *** Fix above errors and then restart with\
 0:46.22                "c:/mozilla-build/mozmake/mozmake.EXE -f client.mk build"
 0:46.22 d:/Pale-Moon/client.mk:372: recipe for target 'configure' failed
 0:46.23 mozmake.EXE[1]: *** [configure] Error 1
 0:46.23 client.mk:386: recipe for target 'd:/Pale-Moon/../UXP-build-palemoon/Makefile' failed
 0:46.23 mozmake.EXE: *** [d:/Pale-Moon/../UXP-build-palemoon/Makefile] Error 2
 0:46.26 90 compiler warnings present.
```

**Comment by mattatobin** [comment]
God damn it.

**Comment by mattatobin** [comment]
God damn fucking Mozilla.

**Comment by mattatobin** [comment]
I never want to hear from heapsnapshot again.
